/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.FonctionsMetier;
import Entity.Region;
import Entity.Visiteurs;
import Model.ModelRegion;
import Model.ModelVisiteur;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author kayum
 */
public class frmStatistiques extends javax.swing.JFrame {

    FonctionsMetier fm;
    ModelRegion mdlRegion;
    ModelVisiteur mdlVisiteur;
    /**
     * Creates new form frmStatistiques
     */
    public frmStatistiques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRegionPlus = new javax.swing.JLabel();
        lblRegionMoins = new javax.swing.JLabel();
        btnSecteurParRegion = new javax.swing.JButton();
        btnVisiteurs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nombres de secteurs par region");

        jLabel2.setText("La region ou travaille le plus de visiteurs:");

        jLabel3.setText("La region ou travaille le moins de visiteurs:");

        jLabel4.setText("Le pourcentage de visiteurs non responsable d'un secteur");

        lblRegionPlus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRegionPlus.setText("jLabel5");

        lblRegionMoins.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRegionMoins.setText("jLabel5");

        btnSecteurParRegion.setText("Secteur par region");
        btnSecteurParRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSecteurParRegionMouseClicked(evt);
            }
        });

        btnVisiteurs.setText("Visiteurs non responsables");
        btnVisiteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisiteursMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSecteurParRegion)
                            .addComponent(jLabel4)
                            .addComponent(btnVisiteurs)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(lblRegionMoins)
                            .addComponent(lblRegionPlus))
                        .addGap(0, 43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSecteurParRegion)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btnVisiteurs)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegionPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblRegionMoins)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        FonctionsMetier fm = new FonctionsMetier();
        lblRegionPlus.setText(fm.getRegionAvecLePlusDeV());
        lblRegionMoins.setText(fm.getRegionAvecLeMoinsDeV());
        
    }//GEN-LAST:event_formWindowOpened

    private void btnSecteurParRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecteurParRegionMouseClicked
        fm = new FonctionsMetier();
        
        DefaultPieDataset monGraph = new DefaultPieDataset();
         for (Region r : fm.getAllRegionsParNbSecteur())
        {
            monGraph.setValue(r.getNomRegion(),r.getNbSecteurParRegion());
        }
        JFreeChart chart1 = ChartFactory.createPieChart(
        "Nombre de secteur par region",
        monGraph,
        true, // légende
        true, // info bulle
        false // url
        );
        ChartFrame frame = new ChartFrame("First", chart1);
        frame.pack();
        frame.setVisible(true);
        
    }//GEN-LAST:event_btnSecteurParRegionMouseClicked

    private void btnVisiteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisiteursMouseClicked
        // TODO add your handling code here:
        
        fm = new FonctionsMetier();
        
        DefaultPieDataset monGraph = new DefaultPieDataset();
         for (Visiteurs v : fm.getPourcentageVisiteurs())
        {
            monGraph.setValue(v.getSecteur().getNomSecteur(),v.getNbVisiteur());
        }
        JFreeChart chart1 = ChartFactory.createPieChart(
        "Nombre de visiteurs non responsable d'un secteur",
        monGraph,
        true, // légende
        true, // info bulle
        false // url
        );
        ChartFrame frame = new ChartFrame("First", chart1);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnVisiteursMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStatistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStatistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStatistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStatistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStatistiques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSecteurParRegion;
    private javax.swing.JButton btnVisiteurs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblRegionMoins;
    private javax.swing.JLabel lblRegionPlus;
    // End of variables declaration//GEN-END:variables
}
